module.exports = {
    PUBLIC_VAPID_KEY: 'BJtgQXRGZg_jEcz_Y1oeJQgDUoxsagG64OrkavrACYEggWo-1bxCjXBXj8LGNB9QzUV67vBOOCs0-0qk52y2Nvw',
    PRIVATE_VAPID_KEY: 'YU2Tc5sXcgHB0NlKVZxTus6fksCMmgLPM8vOnn6DJF0'
}